// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gibbsCpp
List gibbsCpp(List y_list, NumericMatrix y_miss_, NumericMatrix r_obs_, List matList, List pointers, NumericMatrix intercepts_, NumericMatrix fcs_, NumericMatrix peps_, NumericMatrix miss_a_, NumericMatrix miss_b_, NumericMatrix sigma_, NumericMatrix tau_int_, NumericMatrix tau_fc_, NumericMatrix tau_pep_);
RcppExport SEXP _missMS_gibbsCpp(SEXP y_listSEXP, SEXP y_miss_SEXP, SEXP r_obs_SEXP, SEXP matListSEXP, SEXP pointersSEXP, SEXP intercepts_SEXP, SEXP fcs_SEXP, SEXP peps_SEXP, SEXP miss_a_SEXP, SEXP miss_b_SEXP, SEXP sigma_SEXP, SEXP tau_int_SEXP, SEXP tau_fc_SEXP, SEXP tau_pep_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y_miss_(y_miss_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type r_obs_(r_obs_SEXP);
    Rcpp::traits::input_parameter< List >::type matList(matListSEXP);
    Rcpp::traits::input_parameter< List >::type pointers(pointersSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type intercepts_(intercepts_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fcs_(fcs_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type peps_(peps_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type miss_a_(miss_a_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type miss_b_(miss_b_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tau_int_(tau_int_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tau_fc_(tau_fc_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tau_pep_(tau_pep_SEXP);
    rcpp_result_gen = Rcpp::wrap(gibbsCpp(y_list, y_miss_, r_obs_, matList, pointers, intercepts_, fcs_, peps_, miss_a_, miss_b_, sigma_, tau_int_, tau_fc_, tau_pep_));
    return rcpp_result_gen;
END_RCPP
}
// rnormCpp
NumericVector rnormCpp(int n_);
RcppExport SEXP _missMS_rnormCpp(SEXP n_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_(n_SEXP);
    rcpp_result_gen = Rcpp::wrap(rnormCpp(n_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_missMS_gibbsCpp", (DL_FUNC) &_missMS_gibbsCpp, 14},
    {"_missMS_rnormCpp", (DL_FUNC) &_missMS_rnormCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_missMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
