// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gibbsCpp
void gibbsCpp(List y_list, arma::mat y_miss, arma::mat r_obs, List matList, List pointers, arma::mat intercepts, arma::mat fcs, arma::mat peps, arma::mat miss_a, arma::mat miss_b, arma::mat sigma, arma::mat tau_int, arma::mat tau_fc, arma::mat tau_pep);
RcppExport SEXP _missMS_gibbsCpp(SEXP y_listSEXP, SEXP y_missSEXP, SEXP r_obsSEXP, SEXP matListSEXP, SEXP pointersSEXP, SEXP interceptsSEXP, SEXP fcsSEXP, SEXP pepsSEXP, SEXP miss_aSEXP, SEXP miss_bSEXP, SEXP sigmaSEXP, SEXP tau_intSEXP, SEXP tau_fcSEXP, SEXP tau_pepSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y_miss(y_missSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type r_obs(r_obsSEXP);
    Rcpp::traits::input_parameter< List >::type matList(matListSEXP);
    Rcpp::traits::input_parameter< List >::type pointers(pointersSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type fcs(fcsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type peps(pepsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type miss_a(miss_aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type miss_b(miss_bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tau_int(tau_intSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tau_fc(tau_fcSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tau_pep(tau_pepSEXP);
    gibbsCpp(y_list, y_miss, r_obs, matList, pointers, intercepts, fcs, peps, miss_a, miss_b, sigma, tau_int, tau_fc, tau_pep);
    return R_NilValue;
END_RCPP
}
// rnormCpp
NumericVector rnormCpp(int n_);
RcppExport SEXP _missMS_rnormCpp(SEXP n_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_(n_SEXP);
    rcpp_result_gen = Rcpp::wrap(rnormCpp(n_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_missMS_gibbsCpp", (DL_FUNC) &_missMS_gibbsCpp, 14},
    {"_missMS_rnormCpp", (DL_FUNC) &_missMS_rnormCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_missMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
