# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsCpp <- function(y_list, y_miss, r_obs, matList, pointers, intercepts, fcs, peps, miss_a, miss_b, sigma, tau_int, tau_fc, tau_pep) {
    invisible(.Call('_missMS_gibbsCpp', PACKAGE = 'missMS', y_list, y_miss, r_obs, matList, pointers, intercepts, fcs, peps, miss_a, miss_b, sigma, tau_int, tau_fc, tau_pep))
}

#' @export
rnormCpp <- function(n_) {
    .Call('_missMS_rnormCpp', PACKAGE = 'missMS', n_)
}

