# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate a random number from an extended skew normal distribution
#'
#' @param n_ The number of random variates to create
#' @param xi esn parameter
#' @param omega esn parameter
#' @param alpha esn parameter
#' @param tau esn parameter
#'
#' @export
resn <- function(n_, xi, omega, alpha, tau) {
    .Call('_missMS_resn', PACKAGE = 'missMS', n_, xi, omega, alpha, tau)
}

#' @export
resn2 <- function(n_, xi, omega, alpha, tau) {
    .Call('_missMS_resn2', PACKAGE = 'missMS', n_, xi, omega, alpha, tau)
}

testfn <- function(x) {
    .Call('_missMS_testfn', PACKAGE = 'missMS', x)
}

#' @export
rnormCpp <- function(n_) {
    .Call('_missMS_rnormCpp', PACKAGE = 'missMS', n_)
}

