# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsCpp <- function(y_list, y_miss_, r_obs_, matList, pointers, fcs_, peps_, int_mu_, miss_a_, miss_b_, sigma_, tau_int_, tau_fc_, tau_pep_, yVec_, rProbit, rsn, resids_, fc_prior) {
    .Call('_missMS_gibbsCpp', PACKAGE = 'missMS', y_list, y_miss_, r_obs_, matList, pointers, fcs_, peps_, int_mu_, miss_a_, miss_b_, sigma_, tau_int_, tau_fc_, tau_pep_, yVec_, rProbit, rsn, resids_, fc_prior)
}

#' @export
rnormCpp <- function(n_) {
    .Call('_missMS_rnormCpp', PACKAGE = 'missMS', n_)
}

